--Elimina tablas
DROP TABLE detalle_envio CASCADE CONSTRAINTS;
DROP TABLE envio_bodega CASCADE CONSTRAINTS;
DROP TABLE estado_envio CASCADE CONSTRAINTS;

DROP TABLE detalle_venta CASCADE CONSTRAINTS;
DROP TABLE venta CASCADE CONSTRAINTS;

DROP TABLE lote_stock CASCADE CONSTRAINTS;
DROP TABLE alerta_inventario CASCADE CONSTRAINTS;

DROP TABLE medicamento CASCADE CONSTRAINTS;
DROP TABLE tipo_receta CASCADE CONSTRAINTS;
DROP TABLE categoria_medicamento CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;
DROP TABLE empleado CASCADE CONSTRAINTS;
DROP TABLE cargo CASCADE CONSTRAINTS;

DROP TABLE sucursal CASCADE CONSTRAINTS;
DROP TABLE tipo_sucursal CASCADE CONSTRAINTS;
DROP TABLE comuna CASCADE CONSTRAINTS;
DROP TABLE region CASCADE CONSTRAINTS;

--Secuencias
CREATE SEQUENCE seq_id_venta START WITH 020000000000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_id_detalle_venta START WITH 030000000000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_id_envio_bodega START WITH 040000000000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_id_detalle_envio START WITH 050000000000001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_id_alerta_inventario START WITH 060000000000001 INCREMENT BY 1 NOCACHE NOCYCLE;

